# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build-image:
    cmds:
      - nerdctl build --platform=amd64,arm64 -t custom-errors:latest .

  tag:
    cmds:
     - nerdctl tag custom-errors:latest harbor.thurlow.house/registry/custom-errors:latest


  push:
    cmds:
     - nerdctl push --all-platforms harbor.thurlow.house/registry/custom-errors:latest
