apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-errors
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: custom-errors
  template:
    metadata:
      labels:
        app: custom-errors
    spec:
      nodeSelector:
        kubernetes.io/hostname: rk1.thurlow.house
      containers:
        - image: harbor.thurlow.house/registry/custom-errors:latest
          name: custom-errors
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1
              memory: 2G
            requests:
              cpu: 500m
              memory: 1G
