apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-errors
spec:
  errors:
    status:
      - "404"
      - "500"
    query: /{status}.html
    service:
      name: custom-errors
      port: 80
