apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: custom-errors
spec:
  errors:
    status:
      - "400"
      - "404"
      - "401-499"
      - "500"
      - "501-599"
    query: /errors/{status}/
    service:
      name: custom-errors
      port: 80
